defaults: &defaults
  working_directory: ~/roda-api
  docker:
    - image: cimg/ruby:3.1.1-node
      environment:
        RACK_ENV: test
        DB_HOST: 127.0.0.1
        DB_USER: root

    - image: cimg/postgres:14.2
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: ""
        POSTGRES_DB: roda_api_test

references:
  install_bundler: &install_bundler
    run:
      name: Installing bundler
      command: gem i bundler -v $(tail -1 Gemfile.lock | tr -d ' ')

  restore_bundle_cache: &restore_bundle_cache
    restore_cache:
      keys:
        - roda-api-{{ checksum "Gemfile" }}

  bundle_install: &bundle_install
    run:
      name: Installing gems
      command: |
            bundle config set --local path 'vendor/bundle'
            bundle install

  save_bundle_cache: &save_bundle_cache
    save_cache:
      key: roda-api-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle

version: 2
jobs:
  linters:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Installing dependency for undercover gem
          command: sudo apt-get install cmake

      - <<: *install_bundler
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache

      - run:
          name: Running overcommit
          command: |
            bundle exec overcommit -s
            SKIP=AuthorEmail,AuthorName bundle exec overcommit -r

  tests:
    <<: *defaults

    environment:
      - CIRCLE_CI: true
      - RACK_ENV: test
      - DATABASE_URL: "postgres://root@localhost:5432/roda_api_test"

    steps:
      - checkout

      - run:
          name: Installing dependency for undercover gem
          command: sudo apt-get install cmake

      - <<: *install_bundler
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Creating database
          command: bundle exec rake db:create

      - run:
          name: Loading schema
          command: bundle exec rake db:migrate

      - run:
          name: Running tests
          command: bundle exec rspec

      - run:
          name: Coverage
          command: bundle exec undercover -c origin/develop

      - store_artifacts:
          path: ~/roda-api/coverage
          destination: coverage

workflows:
  version: 2
  build:
    jobs:
      - linters
      - tests
