defaults: &defaults
  working_directory: ~/roda-api
  docker:
    - image: circleci/ruby:2.7.1-node

references:
  install_bundler: &install_bundler
    run:
      name: Installing bundler
      command: gem i bundler -v $(tail -1 Gemfile.lock | tr -d ' ')

  restore_bundle_cache: &restore_bundle_cache
    restore_cache:
      keys:
        - roda-api-{{ checksum "Gemfile" }}

  bundle_install: &bundle_install
    run:
      name: Installing gems
      command: bundle install --path vendor/bundle

  save_bundle_cache: &save_bundle_cache
    save_cache:
      key: roda-api-{{ checksum "Gemfile" }}
      paths:
        - vendor/bundle

version: 2
jobs:
  linters:
    <<: *defaults

    steps:
      - checkout

      - <<: *install_bundler
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache

      - run:
          name: Running overcommit
          command: |
            bundle exec overcommit -s
            SKIP=AuthorEmail,AuthorName bundle exec overcommit -r

  tests:
    <<: *defaults

    steps:
      - checkout

      - <<: *install_bundler
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache

      - run:
          name: Running tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - linters
      - tests
